# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  relaese:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macos-10.15]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - name: 安装依赖
      run: |
        npm i
        cd app
        npm i

    - name: 构建window
      if: matrix.os == 'windows-2019'
      run: npm run pack:win
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
 
    - name: 构建mac
      if: matrix.os == 'macos-10.15'
      run: npm run pack:mac
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: 清除其他文件
      if: matrix.os = 'window-2019'
      run: npx rimraf "dist/!(*.exe)"
    - name: 清除其他文件
      if: matrix.os = 'macos-10.15'
      run: npx rimraf "dist/!(*.dmg)"

    - name: 发布
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
